# -*- coding: utf-8 -*-
"""hugging_face.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k9bOn1X6XYSezL-pabGPnk9pBjfH2I8q

#Tokenization
"""

!nvidia-smi

from transformers import AutoModelForSequenceClassification
from transformers import pipeline

model_name = "nlptown/bert-base-multilingual-uncased-sentiment"
classifier = pipeline("sentiment-analysis", model = model_name)
res = classifier("I was so not happy with the titanic movie")
print(res)

from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
text = 'I was so not happy with the titanic movie'
tokens = tokenizer.tokenize(text)
print(tokens)

#convert tokens to input ids
input_ids = tokenizer.convert_tokens_to_ids(tokens)
print("Input Ids",input_ids)

#Encode the text (tokenization + converting to input ids)
encoded_input = tokenizer(text)
print("Encoded Input",encoded_input)

# Decode the text
decoded_output = tokenizer.decode(input_ids)
print("Decoded Output:",decoded_output)

